### ISSUE TITLE
TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by nhduong29** [rsuite/rsuite#1550]
### What version of rsuite are you using?

"rsuite": "^4.8.4",

### What version of React are you using?

"react": "^17.0.1"

### What browser are you using?

Chrome

### Describe the Bug

I follow this to override the icon font. I want to get the font locally.
`@icon-font-path: "./fonts"`
https://rsuitejs.com/guide/use-with-create-react-app/

Then I got this error:
```
Failed to compile
./node_modules/rsuite/lib/styles/themes/default/index.less (./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js!./node_modules/file-loader/dist/cjs.js??ref--6-oneOf-8!./node_modules/rsuite/lib/styles/themes/default/index.less)
TypeError: this.getOptions is not a function
```

### To Reproduce

Just follow the step here: https://rsuitejs.com/guide/use-with-create-react-app/

**Comment by eDubrovsky** [comment]
I downgraded from "less-loader": "^8.0.0" to "less-loader": "^7.3.0" and it's works for me.

**Comment by nhduong29** [comment]
Hi @eDubrovsky ,

Thank you bro, It's working with 7.3.0 (like)

**Comment by eDubrovsky** [comment]
@nhduong29 and can you fix rsuit for new version of the less-loader? :)
