### ISSUE TITLE
Typescript error after updating 5.53.2 to 5.56.0

### ISSUE THREAD

**Issue by b1rdex** [rsuite/rsuite#3683]
### What version of rsuite are you using?

5.56.0

### What version of React are you using?

^18.2.0

### What version of TypeScript are you using (if any)?

^5.1.6

### Describe the Bug

```
Error: node_modules/rsuite/esm/InlineEdit/InlineEdit.d.ts(4,18): error TS2430: Interface 'InlineEditProps' incorrectly extends interface 'WithAsProps<ElementType<any, keyof IntrinsicElements>>'.
  Types of property 'children' are incompatible.
    Type 'ReactElement<any, string | JSXElementConstructor<any>> | ((props: ChildrenProps, ref: Ref<any>) => ReactElement<any, string | JSXElementConstructor<...>>) | undefined' is not assignable to type 'ReactNode'.
      Type '(props: ChildrenProps, ref: Ref<any>) => ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
```

### Expected Behavior

The error is not related to app codebase. Actually, we don't event reference `InlineEdit` in our code base.

Also, please note that there was no error on v5.53.2

### To Reproduce
```
{
  "name": "redacted",
  "private": true,
  "dependencies": {
    "@hookform/resolvers": "^3.3.4",
    "@mantine/hooks": "^7.6.1",
    "@sentry/cli": "^2.27.0",
    "@sentry/react": "^7.101.1",
    "axios": "^1.6.7",
    "baobab": "^2.6.1",
    "baobab-react": "^4.0.2",
    "bootstrap": "^5.3.3",
    "bootstrap-icons": "^1.11.3",
    "casbin.js": "^0.5.1",
    "classnames": "^2.5.1",
    "decimal.js": "^10.4.3",
    "diff": "^5.2.0",
    "emoji-picker-react": "^4.7.12",
    "eslint": "^8.57.0",
    "http-proxy-middleware": "^2.0.6",
    "husky": "^9.0.11",
    "lightgallery": "^2.7.2",
    "lint-staged": "^15.2.2",
    "lodash": "^4.17.21",
    "moment": "^2.30.1",
    "prettier": "^3.1.1",
    "react": "^18.2.0",
    "react-content-loader": "^6.2.1",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.50.1",
    "react-input-mask": "^2.0.4",
    "react-intl": "^6.6.2",
    "react-router-dom": "^6.22.1",
    "react-scripts": "^5.0.1",
    "react-select": "^5.8.0",
    "react-toastify": "^10.0.4",
    "react-top-loading-bar": "^2.3.1",
    "rsuite": "^5.56.0",
    "sass": "^1.71.1",
    "swr": "^2.2.5",
    "uuid": "^9.0.1",
    "validator": "^13.11.0",
    "yup": "^1.4.0"
  },
  "devDependencies": {
    "@formatjs/cli": "^6.2.7",
    "@types/diff": "^5.0.9",
    "@types/node": "^20.11.24",
    "@types/react": "^18.2.56",
    "@types/react-dom": "^18.2.21",
    "@types/react-input-mask": "^3.0.5",
    "@types/uuid": "^9.0.8",
    "@types/validator": "^13.11.9",
    "eslint-plugin-formatjs": "^4.12.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "eject": "react-scripts eject",
    "prepare": "husky install",
    "test": "eslint --fix src/ && tsc --noEmit",
    "i18n:extract-messages": "formatjs extract 'src/**/*.ts*' --ignore='**/*.d.ts' --out-file src/lang/ru.json --id-interpolation-pattern '[sha512:contenthash:base64:6]'"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ],
    "plugins": [
      "formatjs"
    ],
    "rules": {
      "jsx-a11y/alt-text": "off",
      "formatjs/no-offset": "error",
      "formatjs/enforce-description": [
        "error",
        "literal"
      ],
      "formatjs/enforce-default-message": [
        "error",
        "literal"
      ],
      "formatjs/enforce-placeholders": "error",
      "formatjs/no-camel-case": "error",
      "formatjs/no-multiple-whitespaces": "error",
      "formatjs/enforce-id": [
        "error",
        {
          "idInterpolationPattern": "[sha512:contenthash:base64:6]",
          "idWhitelist": [
            ".+"
          ]
        }
      ]
    }
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "overrides": {
    "@typescript-eslint/typescript-estree": "v6.2.0",
    "@typescript-eslint/parser": "v6.2.0",
    "@typescript-eslint/eslint-plugin": "v6.2.0",
    "fork-ts-checker-webpack-plugin": "^6.5.3",
    "typescript": "^5.1.6",
    "@types/trusted-types": "^2.0.3"
  }
}
```

**Comment by b1rdex** [comment]
A possible solution: replace 
```
export interface InlineEditProps extends WithAsProps {
```
with
```
export interface InlineEditProps extends Omit<WithAsProps, 'children'> {
```

**Comment by simonguo** [comment]
Fixed in [v5.57.0](https://github.com/rsuite/rsuite/releases/tag/v5.57.0)
